### PR TITLE
Make sure binlog_dir is owned by user

### PR DESCRIPTION
**Pull request by bracki**
Make sure binlog_dir is owned by `$user` so that resource defaults overrides do not mess it up.

### CODE REVIEW

**Comment by bracki** [comment]
Test is missing. Will add.

**Comment by mlafeldt** [comment]
Cool! What about the permissions of the config file? Is the default (root) OK here?

**Comment by mlafeldt** [comment]
Well, it's /etc/default/beanstalkd, so root should be OK.

**Comment by mlafeldt** [comment]
Great!

**Pull request merged**
